# Book settings
title: 地理空间数据科学基础12
author: 兰小机 吴启用 石林
copyright: "2023" # Copyright year to be placed in the footer
logo: logo.png # A path to the book logo

#######################################################################################
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
# exclude_patterns: [ ]
# Auto-exclude files not in the toc
only_build_toc_files: true

#######################################################################################
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

#######################################################################################
launch_buttons: 
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/landcom8835/gdsbook-rep/  # Online location of this book
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# HTML-specific settings
html:
  favicon: "icon.png"
  baseurl: "https://landcom8835.github.io/gdsbook-rep/" # The base URL where your book will be hosted.
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  use_download_button: false
