channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - jupyterlab>3
  - ipython
  - jupyter-book
  - jupytext
  - myst-nb
  - myst-parser
  - numpy
  - shapely
  - pandas
  - geopandas
  - pygeos
  - rasterio
  - rasterstats
  - matplotlib
  - mapclassify
  - cartopy
  - contextily
  - geoplot
  - ipympl
  - ipyleaflet
  - folium
  - hvplot
  - geoviews
  - pyepsg